# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_headimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='文章内容'),
        ),
    ]
