# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170310_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='哈哈', max_length=500, verbose_name='文章简介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=1000000, verbose_name='文章内容'),
        ),
    ]
